export const UPDATE_COMPONENTS_LOADING = 'UPDATE_COMPONENTS_LOADING';
export const UPDATE_COMPONENTS_FAILURE = 'UPDATE_COMPONENTS_FAILURE';
export const UPDATE_COMPONENTS_SUCCESS = 'UPDATE_COMPONENTS_SUCCESS';

export const FETCH_COMPONENTS_LOADING = 'FETCH_COMPONENTS_LOADING';
export const FETCH_COMPONENTS_FAILURE = 'FETCH_COMPONENTS_FAILURE';
export const FETCH_COMPONENTS_SUCCESS = 'FETCH_COMPONENTS_SUCCESS';
