export const FETCH_COMPONENTS = 'FETCH_COMPONENTS';
export const FETCH_COMPONENTS_LOADING = 'FETCH_COMPONENTS_LOADING';
export const FETCH_COMPONENTS_FAILURE = 'FETCH_COMPONENTS_FAILURE';
export const FETCH_COMPONENTS_SUCCESS = 'FETCH_COMPONENTS_SUCCESS';

export const UPDATE_COMPONENT_LOADING = 'UPDATE_COMPONENT_LOADING';
export const UPDATE_COMPONENT_FAILURE = 'UPDATE_COMPONENT_FAILURE';
export const UPDATE_COMPONENT_SUCCESS = 'UPDATE_COMPONENT_SUCCESS';

export const ADD_COMPONENT = 'ADD_COMPONENT';
export const ADD_COMPONENT_LOADING = 'ADD_COMPONENT_LOADING';
export const ADD_COMPONENT_FAILURE = 'ADD_COMPONENT_FAILURE';
export const ADD_COMPONENT_SUCCESS = 'ADD_COMPONENT_SUCCESS';
