export const FETCH_HIERARCHY_LOADING = 'FETCH_HIERARCHY_LOADING';
export const FETCH_HIERARCHY_FAILURE = 'FETCH_HIERARCHY_FAILURE';
export const FETCH_HIERARCHY_SUCCESS = 'FETCH_HIERARCHY_SUCCESS';

export const TOGGLE_HIERARCHY_MODE = 'TOGGLE_HIERARCHY_MODE';
export const UPDATE_CURRENT_PATH = 'UPDATE_CURRENT_PATH';
export const TOGGLE_CUSTOMIZATION_DRAWER = 'TOGGLE_CUSTOMIZATION_DRAWER';
