export const FETCH_HIERARCHY_LOADING = 'FETCH_HIERARCHY_LOADING';
export const FETCH_HIERARCHY_FAILURE = 'FETCH_HIERARCHY_FAILURE';
export const FETCH_HIERARCHY_SUCCESS = 'FETCH_HIERARCHY_SUCCESS';

export const SET_HIERARCHY_MODE = 'SET_HIERARCHY_MODE';
