export const FETCH_HIERARCHY = 'FETCH_HIERARCHY';
export const FETCH_HIERARCHY_LOADING = 'FETCH_HIERARCHY_LOADING';
export const FETCH_HIERARCHY_FAILURE = 'FETCH_HIERARCHY_FAILURE';
export const FETCH_HIERARCHY_SUCCESS = 'FETCH_HIERARCHY_SUCCESS';

export const ADD_HIERARCHY_LOADING = 'ADD_HIERARCHY_LOADING';
export const ADD_HIERARCHY_FAILURE = 'ADD_HIERARCHY_FAILURE';
export const ADD_HIERARCHY_SUCCESS = 'ADD_HIERARCHY_SUCCESS';

export const TOGGLE_HIERARCHY_MODE = 'TOGGLE_HIERARCHY_MODE';
export const UPDATE_CURRENT_PATH = 'UPDATE_CURRENT_PATH';
export const SET_CURRENT_HIERARCHY = 'SET_CURRENT_HIERARCHY';

export const UPDATE_HIERARCHY_LOADING = 'UPDATE_HIERARCHY_LOADING';
export const UPDATE_HIERARCHY_FAILURE = 'UPDATE_HIERARCHY_FAILURE';
export const UPDATE_HIERARCHY_SUCCESS = 'UPDATE_HIERARCHY_SUCCESS';

export const DELETE_HIERARCHY_LOADING = 'DELETE_HIERARCHY_LOADING';
export const DELETE_HIERARCHY_FAILURE = 'DELETE_HIERARCHY_FAILURE';
export const DELETE_HIERARCHY_SUCCESS = 'DELETE_HIERARCHY_SUCCESS';

export const FETCH_ATTACHMENTS_LOADING = 'FETCH_ATTACHMENTS_LOADING';
export const FETCH_ATTACHMENTS_FAILURE = 'FETCH_ATTACHMENTS_FAILURE';
export const FETCH_ATTACHMENTS_SUCCESS = 'FETCH_ATTACHMENTS_SUCCESS';

export const UPDATE_ATTACHMENTS_LOADING = 'UPDATE_ATTACHMENTS_LOADING';
export const UPDATE_ATTACHMENTS_FAILURE = 'UPDATE_ATTACHMENTS_FAILURE';
export const UPDATE_ATTACHMENTS_SUCCESS = 'UPDATE_ATTACHMENTS_SUCCESS';

export const DELETE_ATTACHMENT_CLIENT = 'DELETE_ATTACHMENT_CLIENT';
export const ADD_ATTACHMENT_CLIENT = 'ADD_ATTACHMENT_CLIENT';
